### ISSUE TITLE
Exclude multiple folders

### ISSUE THREAD

**Issue by RealHarshThakur** [reviewdog/action-shellcheck#14]
How do I exclude multiple folders? I have tried :
`exclude: './.git/* , ./vendor/*'`
`exclude: './.git/* ./vendor/*'`

**Comment by alan-barzilay** [comment]
I'm having the same problem to input multiple patterns, but it looks like this may not be something currently supported. @haya14busa would you mind clarifying if this is possible?

**Comment by evulhotdog** [comment]
https://github.com/marketplace/actions/run-misspell-with-reviewdog#exclude

It appears for other reviewdog actions, you can provide multiple.

**Comment by evulhotdog** [comment]
The way that this is built doesn't support multiple paths from what I can tell, unless you can somehow glob multiple paths.

https://github.com/reviewdog/action-shellcheck/blob/master/script.sh#L16

```
FILES=$(find "${INPUT_PATH:-'.'}" -not -path "${INPUT_EXCLUDE}" -type f -name "${INPUT_PATTERN:-'*.sh'}")
```

A fix could be to change it to use regex instead of globbing, using the the `egrep` regextype:

```
find . -regextype egrep -not -regex '(./roles/foo/files/installer.*|./roles/bar/templates/callhome.j2.sh)' -type f -name '*.sh'
```

**Comment by grische** [comment]
If anyone wants to pick this up:
The code from `action-misspell` should be easy to add to this action as well by moving from `/bin/sh` to `/bin/bash`
https://github.com/reviewdog/action-misspell/blob/fc256d61e34b3fab7ee51c6e608b6d7de88895c5/entrypoint.sh#L20-L23

From what I can tell, only those few lines need adjusting:
* https://github.com/reviewdog/action-shellcheck/blob/a545b1687db513080ccd410c02e132d268d33801/script.sh#L1
* https://github.com/reviewdog/action-shellcheck/blob/a545b1687db513080ccd410c02e132d268d33801/script.sh#L17
* https://github.com/reviewdog/action-shellcheck/blob/a545b1687db513080ccd410c02e132d268d33801/script.sh#L21
* https://github.com/reviewdog/action-shellcheck/blob/a545b1687db513080ccd410c02e132d268d33801/script.sh#L26
